# Generated by Django 4.2.11 on 2025-04-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0005_manufacturer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='annual_volume',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='shipping_terms',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='unit_price',
        ),
    ]
