# Generated by Django 5.1.6 on 2025-04-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_quoterequest_accepted_bid'),
        ('supplier', '0004_bid_payment_status_bid_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='supplier.bid')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='supplier.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
