# Generated by Django 5.1.6 on 2025-04-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplierreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
