# Generated by Django 5.1.7 on 2025-04-04 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_bid_feedback_given_supplier_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='aircraft_type',
            field=models.CharField(blank=True, choices=[('cargo_plane', 'Cargo Plane'), ('passenger_plane', 'Passenger Plane (Cargo Hold)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='calculated_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='empty_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='flight_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='load_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='transport_mode',
            field=models.CharField(choices=[('road', 'Road Transport'), ('air', 'Air Transport')], default='road', max_length=20),
        ),
        migrations.AddField(
            model_name='bid',
            name='vehicle_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('small_truck', 'Small Truck (3.5-7.5 tons)'), ('medium_truck', 'Medium Truck (7.5-16 tons)'), ('large_truck', 'Large Truck (16-32 tons)'), ('articulated_truck', 'Articulated Truck (>32 tons)')], max_length=20, null=True),
        ),
    ]
