# Generated by Django 5.1.6 on 2025-04-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_bid_aircraft_type_bid_calculated_emissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='commodity_categories',
            field=models.JSONField(default=list, help_text='List of commodity categories this supplier deals in'),
        ),
    ]
