# Generated by Django 5.1.6 on 2025-04-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_supplier_commodity_categories'),
        ('supplier', '0008_supplierinventory'),
    ]

    operations = [
    ]
